test_batch_size: 100
batch_size: 128
num_microbatches: 128
lr: 0.001
momentum: 0.9
decay: 5e-4
epochs: 40
n_train: 90000
save_on_epochs: [39]

# Instead of computing the noise variance sigma = z * S,
# since we are not using clipping (S is undefined/infinite),
# we explicitly set sigma.
S: inf
sigma: 1.0
dp: True

criterion: mse

save_model: True
dataset: imdb-wiki
model: regressionnet
scheduler: False
optimizer: Adam


root_dir: /projects/grail/jpgard/imdb-wiki
multi_gpu: False