test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.001
momentum: 0.9
decay: 5e-4
dp: False
epochs: 40
n_train: 90000
save_on_epochs: [39]

criterion: mse

save_model: True
dataset: imdb-wiki
model: PretrainedRegressionRes
resnet_depth: 18
freeze_pretrained_weights: False
scheduler: False
optimizer: SGD


root_dir: /projects/grail/jpgard/imdb-wiki
multi_gpu: False
